"""
Pydantic v2 configs for the graph nodes.

The deep-learning node is wired up for torch (replacing the qxcl keras path).
The user is expected to train a torch `nn.Module` on data generated by the
iterative SC potential node and supply its weights via `model_base_dir`.
"""

from __future__ import annotations

from os.path import exists, join
from typing import Annotated, Any, Literal, Optional, Union

import torch
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)

from simulator.computational_graph.utils.device_config import DeviceConfig

DimensionType = Union[list[int], int, None]


class NodeConnection(BaseModel):
    input_data_names: list[str]
    output_data_names: list[str]


class BaseNodeConfig(BaseModel):
    """Base config shared by all graph nodes."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str
    connections: NodeConnection

    supports_batching: bool = False

    input_dimensions: DimensionType = None
    output_dimensions: DimensionType = None

    num_cpu: int = 1

    @field_validator("connections", mode="before")
    @classmethod
    def connections_check(cls, v: Any) -> NodeConnection:
        if isinstance(v, dict):
            v = NodeConnection(**v)
        assert len(v.input_data_names) > 0, "No input data names provided"
        assert len(v.output_data_names) > 0, "No output data names provided."
        return v

    @model_validator(mode="after")
    def coerce_and_check_dimensions(self) -> "BaseNodeConfig":
        for attr in ("input_dimensions", "output_dimensions"):
            v = getattr(self, attr)
            if v is None:
                if self.supports_batching:
                    continue
                raise ValueError(
                    f"If the node doesn't support batching, {attr} must be provided"
                )
            names = (
                self.connections.input_data_names
                if attr == "input_dimensions"
                else self.connections.output_data_names
            )
            n = len(names)
            if isinstance(v, int):
                assert n == 1, f"1 dimension given, {n} required for {attr}"
                v = [v]
                setattr(self, attr, v)
            assert len(v) == n, f"Mismatched {attr} length: got {len(v)}, need {n}."
        return self


class DeepLearningBaseNodeConfig(BaseNodeConfig):
    """
    Config for nodes wrapping a torch model.

    `model_base_dir` should contain a file named `final_model.pt` (a
    `torch.save`-d `state_dict` or a TorchScript module). Loading logic
    lives in `simulator.computational_graph.graph_nodes.deep_learning_base_node`.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True, from_attributes=True)

    model_base_dir: str
    model: Optional[torch.nn.Module] = None
    device: str = "cpu"

    supports_batching: bool = True

    @model_validator(mode="after")
    def check_model_dir_exists(self) -> "DeepLearningBaseNodeConfig":
        if self.model is None and not exists(self.model_base_dir):
            raise FileNotFoundError(
                f"model_base_dir {self.model_base_dir} does not exist and no model was provided."
            )
        return self


class SCPotentialDeepLearningNodeConfig(DeepLearningBaseNodeConfig):
    node_class: Literal["SelfConsistentPotentialDeepLearningNode"] = (
        "SelfConsistentPotentialDeepLearningNode"
    )
    name: str = "self_consistent_potential_model"
    image_slice: int = 1
    device_config: Optional[DeviceConfig] = None

    connections: NodeConnection = NodeConnection(
        input_data_names=["electrostatic_potential"],
        output_data_names=["self_consistent_potential"],
    )
    input_dimensions: DimensionType = 2
    output_dimensions: DimensionType = 2


class InitialPotentialNodeConfig(BaseNodeConfig):
    node_class: Literal["InitialElectroStaticPotential"] = "InitialElectroStaticPotential"
    name: str = "initial_electrostatic_potential"

    connections: NodeConnection = NodeConnection(
        input_data_names=["gate_voltages"],
        output_data_names=["electrostatic_potential"],
    )
    input_dimensions: DimensionType = 1
    output_dimensions: DimensionType = 2

    device_config: Optional[DeviceConfig] = None

    model_config = ConfigDict(from_attributes=True)


class SCPotentialIterativeNodeConfig(BaseNodeConfig):
    node_class: Literal["IterativeSelfConsistentPotentialNode"] = (
        "IterativeSelfConsistentPotentialNode"
    )
    name: str = "iterative_self_consistent_potential"
    connections: NodeConnection = NodeConnection(
        input_data_names=["electrostatic_potential"],
        output_data_names=["self_consistent_potential_iterative"],
    )
    input_dimensions: DimensionType = 2
    output_dimensions: DimensionType = 2

    device_config: Optional[DeviceConfig] = None

    supports_batching: bool = True


class LoGDotDetectionNodeConfig(BaseNodeConfig):
    node_class: Literal["LoGQuantumDotDetectionNode"] = "LoGQuantumDotDetectionNode"
    name: str = "LoG_dot_counter"
    connections: NodeConnection = NodeConnection(
        input_data_names=["self_consistent_potential"],
        output_data_names=["dots"],
    )
    device_config: Optional[DeviceConfig] = None
    image_slice: int = 1

    input_dimensions: DimensionType = 2
    output_dimensions: DimensionType = 1


class CarrierDensityNodeConfig(BaseNodeConfig):
    node_class: Literal["CarrierDensityNode"] = "CarrierDensityNode"
    name: str = "Carrier_density_node"

    connections: NodeConnection = NodeConnection(
        input_data_names=["self_consistent_potential"],
        output_data_names=["carrier_density"],
    )
    device_config: Optional[DeviceConfig] = None

    input_dimensions: DimensionType = 2
    output_dimensions: DimensionType = 2


class CapacitanceNodeConfig(BaseNodeConfig):
    node_class: Literal["DotOccupationCapacitanceNode"] = "DotOccupationCapacitanceNode"
    name: str = "Dot_occupation_capacitance_model"
    connections: NodeConnection = NodeConnection(
        input_data_names=["self_consistent_potential", "dots"],
        output_data_names=["dots_with_occupation", "energy_matrix"],
    )
    device_config: Optional[DeviceConfig] = None

    input_dimensions: DimensionType = [2, 1]
    output_dimensions: DimensionType = [1, 2]


class TransportNodeConfig(BaseNodeConfig):
    node_class: Literal["SemiClassicalTransportNode"] = "SemiClassicalTransportNode"
    device_config: Optional[DeviceConfig] = None
    name: str = "SemiClassical_transport_model"
    connections: NodeConnection = NodeConnection(
        input_data_names=["self_consistent_potential"],
        output_data_names=["trajectory", "minimax"],
    )
    input_dimensions: DimensionType = 2
    output_dimensions: DimensionType = [2, 1]
    information: bool = False
    potential_cut: int = 1
    random_trajectory: bool = False


class DoubleDotTunnelCouplingNodeConfig(BaseNodeConfig):
    node_class: Literal["DoubleDotTunnelCouplingNode"] = "DoubleDotTunnelCouplingNode"
    device_config: Optional[DeviceConfig] = None
    name: str = "double_dot_tunnel_coupling"
    k: int = 2
    plot_probability_density: bool = False
    tunneling_estimator: str = "wannier"
    lattice_shape: tuple[int, int] = (50, 50)
    connections: NodeConnection = NodeConnection(
        input_data_names=["self_consistent_potential", "dots"],
        output_data_names=["tunnel_coupling"],
    )
    input_dimensions: DimensionType = [2, 1]
    output_dimensions: DimensionType = 1

    @field_validator("tunneling_estimator")
    @classmethod
    def check_tunneling_estimator(cls, v: str) -> str:
        if v.lower() not in ["wannier", "excited_state"]:
            raise ValueError("tunneling_estimator must be either 'wannier' or 'excited_state'")
        return v


NodeConfigsGroup = Annotated[
    Union[
        CapacitanceNodeConfig,
        LoGDotDetectionNodeConfig,
        SCPotentialIterativeNodeConfig,
        InitialPotentialNodeConfig,
        SCPotentialDeepLearningNodeConfig,
        TransportNodeConfig,
        DoubleDotTunnelCouplingNodeConfig,
        CarrierDensityNodeConfig,
    ],
    Field(discriminator="node_class"),
]
