"""
Torch-backed deep-learning replacement for the iterative self-consistent
potential solver.

The model is expected to map a normalised electrostatic potential image
(shape `(B, 1, H, W)` after pre-processing) to a normalised self-consistent
potential image of the same shape. Train it on data generated by the
iterative SC node and save with `torch.save(module, "final_model.pt")`.
"""

from __future__ import annotations

from os.path import join
from typing import List

import numpy as np

from simulator.computational_graph.graph_nodes.deep_learning_base_node import (
    DeepLearningBaseNode,
)
from simulator.computational_graph.graph_nodes.node_configs import (
    SCPotentialDeepLearningNodeConfig,
)
from simulator.computational_graph.utils.device_config import DeviceConfig
from simulator.deep_learning.normalization import image_preprocess, scale_image_array
from simulator.utils.misc import yaml_safe_load


class SelfConsistentPotentialDeepLearningNode(DeepLearningBaseNode):
    """Graph node that computes the self-consistent potential with a learned model."""

    def __init__(self, node_config: SCPotentialDeepLearningNodeConfig) -> None:
        super().__init__(node_config)

        self.norm: float = 1.0
        self.image_slice = node_config.image_slice

        self.original_shape: List = []
        self.zoom_shape: List = []

        self.scale_factor = self._compute_require_scale_factor(node_config)

    def _compute_require_scale_factor(self, config: SCPotentialDeepLearningNodeConfig) -> float:
        """
        Matches the current device's pixel scale to that of the device the model was
        trained on. The training device's config is expected at
        `{model_base_dir}/configs/graph_config.yaml` and
        `{model_base_dir}/configs/model_config.yaml`.
        """
        if config.device_config is None:
            raise ValueError(f"Node {self.name} has no device config.")
        current_scale = config.device_config.pixel_associated_length * self.image_slice

        original_config_file = join(config.model_base_dir, "configs/graph_config.yaml")
        original_config_dict = yaml_safe_load(original_config_file)
        original_device_config = DeviceConfig(**original_config_dict["device_config"])

        original_model_config_file = join(config.model_base_dir, "configs/model_config.yaml")
        original_model_config = yaml_safe_load(original_model_config_file)

        required_pixel_scale = (
            original_device_config.pixel_associated_length * original_model_config["image_slice"]
        )

        return current_scale / required_pixel_scale

    def _preprocess(self, x: np.ndarray) -> np.ndarray:
        x, norm = image_preprocess(x, image_slice=self.image_slice)
        self.norm = norm

        self.original_shape = list(x.shape)
        self.zoom_shape = list(x.shape)

        dimensions = len(x.shape)
        zoom_axes = [0, 1] if dimensions == 2 else [1, 2]

        for axis in zoom_axes:
            self.zoom_shape[axis] = int(self.zoom_shape[axis] * self.scale_factor)

        scaled_array = scale_image_array(x, self.zoom_shape)

        # Add a channel dim so the torch model sees (B, 1, H, W).
        scaled_array = np.clip(scaled_array, a_min=-1.0, a_max=1.0)
        if scaled_array.ndim == 3:
            scaled_array = scaled_array[:, np.newaxis, ...]
        return scaled_array

    def _postprocess(self, x: np.ndarray) -> np.ndarray:
        # Strip channel dim if present.
        if x.ndim == 4 and x.shape[1] == 1:
            x = np.squeeze(x, axis=1)

        mask = np.sign(x)
        x = x**2 * mask
        x = x * self.norm

        x = scale_image_array(x, self.original_shape)
        return np.squeeze(x)
