"""
Graph node to iteratively solve for the self-consistent electrostatic potential
and charge carrier density due to the presence of charge carriers.

Copyright © 2022 QuantrolOx Ltd
"""

from typing import List, Optional

import torch
import numpy as np
from scipy.signal import fftconvolve  # type:ignore

from simulator.computational_graph.graph_nodes.abstract_graph_node import AbstractGraphNode
from simulator.computational_graph.graph_nodes.node_configs import SCPotentialIterativeNodeConfig
from simulator.computational_graph.graph_nodes.utils.self_consistent_potential_utils import (
    get_carrier_density,
    get_scale,
    kernel_calc,
    fftconvolve2d
)


class IterativeSelfConsistentPotentialNode(AbstractGraphNode):
    """
    Graph node for calculating self-consistent configuration of charge carriers and the resulting
    total electrostatic potential.
    """

    def __init__(self, node_config: SCPotentialIterativeNodeConfig) -> None:
        """
        Initializes node with name and optional connections.

        Args:
            node_config: configuration parameters for node call
        """
        super().__init__(node_config)

        assert (
            node_config.device_config is not None
        ), "Device config must be provided to self-consistent potential node"
        self.material_config = node_config.device_config.material_config
        self.device_config = node_config.device_config

        # Sets Fermi level to be 0 as in previous simulation. # TODO: device specific Fermi level?
        self.f_level = 0
        self.scale: Optional[np.ndarray] = None
        self.k = None

    # pylint: disable-next=too-many-locals
    def compute(
        self,
        input_potential: Optional[np.ndarray] = None,
        initial_guess:   Optional[np.ndarray] = None,
    ) -> List[np.ndarray]:
        """
        Given an input potential (generated by initial electrostatic potential node), this node
        iteratively solves for both a consistent charge carrier density and a total potential that
        includes the potential generated by the carge carrier density.

        Args:
            input_potential: Initial potential of the device ignoring charge carrier contribution.
            initial_guess:   Optional warm-start for the SC iteration. Pass the
                             converged pot_tot from a previous call to skip
                             most of the convergence transient. Shape must
                             match input_potential (unpadded). If None, the
                             iteration starts from input_potential as before.
        Returns: Self-consistent potential given charge density --> the total device potential in mV
        """
        # if self.information:
        #     print("\nScreening")

        if input_potential is None:
            raise ValueError(
                "Arguments not provided in self-consistent \
                                electrostatic node call method"
            )

        if input_potential.ndim == 2:
            batched_input = False
            input_potential = input_potential[None, ...]  # add batch dim
        else:
            batched_input = True

        self.scale = get_scale(input_potential[0], self.device_config)

        # Length scales
        scale_x, scale_y = self.scale

        # Maximum number of iterations
        n_iter = 500
        # Mixing Parameter alpha
        alpha = 0.005

        # Convergence Error Threshold
        if bool(self.material_config.donors):
            # equivalent to self.add_disorder
            convergence = 10e-3
        else:
            convergence = 1e-3

        b, n, m = input_potential.shape

        # Expand for boundary effects
        k = 4
        pad_width = ((0, 0), (int(n / k), int(n / k)), (int(m / k), int(m / k)))
        input_potential = np.pad(input_potential, pad_width=pad_width, mode="reflect")

        if initial_guess is not None:
            # Warm-start: use the supplied guess as the iteration starting point.
            # Must have the same unpadded shape as input_potential's pre-pad shape.
            if initial_guess.ndim == 2:
                initial_guess = initial_guess[None, ...]
            assert initial_guess.shape == (b, n, m), (
                f"initial_guess shape {initial_guess.shape} does not match "
                f"input_potential's unpadded shape {(b, n, m)}"
            )
            pot_tot = np.pad(initial_guess, pad_width=pad_width, mode="reflect")
        else:
            pot_tot = input_potential

        # if self.add_kernel:
        # self.add_kernel set to True in previous simulator (also seems unanimously necessary)
        self.k = kernel_calc(
            pot_tot[0],
            scale_x,
            scale_y,
            screen=True,
            device_config=self.device_config,
        )

        use_torch = True
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

        if use_torch:
            self.k = torch.tensor(self.k, device=device)
            input_potential = torch.tensor(input_potential, device=device)
            pot_tot = torch.tensor(pot_tot, device=device)

        with torch.no_grad():
                # Relaxation Loop
                err_previous = 1e6
                err = err_previous
                i = 0
                while (err > convergence) and (i < n_iter):
                    # Electron Density
                    carrier_density = get_carrier_density(pot_tot, self.material_config, mu=self.f_level, use_torch=use_torch)
                    # Screening Potential
                    phi_screen = self.screening_potential(carrier_density, use_torch=use_torch)
                    # Add screening to original bare potential
                    pot_tot_cal = input_potential + phi_screen
                    # Under Relaxation
                    pot_tot_update = (1 - alpha) * pot_tot + alpha * pot_tot_cal
                    # Convergence Error
                    distance = torch.abs(pot_tot-pot_tot_update) if use_torch else np.abs(pot_tot - pot_tot_update)
                    err = torch.max(torch.mean(distance, dim=(-2, -1))).item() if use_torch else np.max(np.mean(distance, axis=(1, 2)))
                    # New for next iteration
                    pot_tot = pot_tot_update

                    if i % 10 == 0:
                        print(f"   {i}", f"\t\t{err}")
                        if err > err_previous:
                            alpha = alpha / 2
                            n_iter += 9
                            print(
                                f"Error increasing, decreasing alpha to {alpha} and "
                                f" max iterations to {n_iter}"
                            )

                        err_previous = err

                    i += 1

                pot_tot = pot_tot[..., int(n / k) : int(n + n / k), int(m / k) : int(m + m / k)]

                if use_torch:
                    pot_tot = pot_tot.detach().cpu().numpy()

                if not batched_input:
                    pot_tot = pot_tot.squeeze(0)

                return [pot_tot]

    def screening_potential(self, charge_density, use_torch=False):
        """
        Calculates the Coulomb self-interaction or screening contribtion to the total potential.

        Args:
            charge_density: Charge density of the device.
        """
        scale_x, scale_y = self.scale[0], self.scale[1]

        # Charge
        q = self.material_config.carrier_charge * 1.6e-19
        unit_a = scale_x * scale_y
        charge = unit_a * charge_density * q

        # in mV
        if use_torch:
            scr = fftconvolve2d(charge, self.k[None, :, :], mode="same") * 1e3
        else:
            scr = fftconvolve(charge, self.k[None, :, :], mode="same", axes=(-2, -1)) * 1e3

        return scr